# HUGGINGFACEHUB_API_TOKEN = "hf_..."  # DO NOT commit a real token here.
# Add your Hugging Face token either as an environment variable
# HUGGINGFACEHUB_API_TOKEN (recommended) or fill the line above locally.
# Generate a token at: https://huggingface.co/settings/tokens